version: '2'
services:
  mysqlaut:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: tuapassword
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    networks:
      - authnetwork

  mysql_main:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: tuapassword
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - mynetwork

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test:1:1"
    networks:
      - mynetwork

  authserver:
    ports:
      - "8081:8081"  
    build:
      context: ./Go/
      dockerfile: Server_Auth/dockerfile.auth
    networks:
      - authnetwork

  mainserver:
    ports:
      - "25536:25536"
    build:
      context: ./Go/
      dockerfile: MainServer/Dockerfile.main
    networks:
      - mynetwork
      - authnetwork


  bot_tg:
    build:
      context: ./Python/bot_tg
      dockerfile: dockerfile.bottg
    networks:
      - mynetwork

  server_flask:
    ports:
      - "8888:8888"
    build:
      context: ./Python/server
      dockerfile: dockerfile.server
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge
  authnetwork:
    driver: bridge  
